name: JDRP
favicon: null
layout_spectrum: 0.21208955300971866
typography_spectrum: 0.261317205382511
title: 'JDRP.co - Photo, Video, Web, Social'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040309'
    - '#3e656b'
    - '#95949a'
    - '#cdccd2'
    - '#f6f6f6'
  brandStrength: 1
  lightness: 0.053412220906466246
  saturation: 0.8055930943228304
  rhythmicContrast: 0.35195226944051683
purpose: []
