name: JDRP
favicon: null
layout_spectrum: 1
typography_spectrum: 0.261317205382511
title: 'JDRP.co - Photo, Video, Web, Social'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#393939'
    - '#f4f6f5'
    - '#d0d0ce'
    - '#687472'
    - '#cc433d'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.8055930943228304
  rhythmicContrast: 0.5
purpose: []
